blank_issues_enabled: false
contact_links:
  - name: Contact NLTC 
    url: https://nltelugucommunity.org/contact-us/
    about: To connect with NLTC
  - name: Know more about NLTC 
    url: https://nltelugucommunity.org
    about: About NLTC
